function cellInfo = bus_fun(varargin) 
% BUS_FUN returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'out_rd_bus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'a11', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'a21', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'a12', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'a22', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'b1', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'b2', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'r_d', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
